server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://algaworks-database:3306/algaworks?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&enabledTLSProtocols=TLSv1.2
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
